apiVersion: v1
kind: Service
metadata:
  name: aplikasi-service
spec:
  selector:
    app: aplikasi-web # app label
  type: LoadBalancer # Opening port to local
  ports:
    - protocol: TCP
      port: 8081 # Local Port
      targetPort: 80 # Port on Apache Container
