apiVersion: v1
kind: Service
metadata:
  name: mysql-service # the DNS
  labels:
    app: mysql-app
spec:
  ports:
    - port: 3306 # Port gate
      targetPort: 3306 # Port target container
  selector:
    app: mysql-app # label on mysql-deployment
  type: ClusterIP # Internal only
