apiVersion: v1
kind: Secret
metadata:
  name: uas-db-secret
type: Opaque
data:
  # .env: DB_PASSWORD
  db-password:

  # Isinya: "root" (jika user root) -> cm9vdA==
  # Atau sesuaikan dengan user yang Anda mau
  # .env: DB_PASSWORD
  db-root-password:

  # .env: DB_DATABASE
  db-name:
